module.exports = [
    {
      name: "Macaroni and Cheese",
      type: "lunch",
      description: "A cheesy delight that will not break your calorie budget!",
      photo_URL: "https://homeroom510.com/wp-content/uploads/2015/12/9041-classic.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "12:00:00",
      quantity: 7
    },
    {
      name: "Homemade Pizza",
      type: "dinner",
      description: "A great blend of italian herbs, spinach, and three cheese. This pizza is a family tradition.",
      photo_URL: "http://yesofcorsa.com/wp-content/uploads/2018/07/Homemade-Pizza-Wallpaper-HQ.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "19:00:00",
      quantity: 5
    }, {
      name: "Spring Bean Salad",
      type: "lunch",
      description: "A protein rich salad that will energize your afternoon.",
      photo_URL: "https://noblepig.com/site/wp-content/uploads/2016/06/1Avocado-and-Three-Bean-Salad-is-a-refreshing-salad-for-all-your-entertaining-needs.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 0,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 1,
      date_available: "2019-04-21",
      time_available: "13:00:00",
      quantity: 10
    }, {
      name: "Avacado and Chicken Salad",
      type: "dinner",
      description: "Scrumptious and meaty, yet smooth and flavorful.",
      photo_URL: "https://gimmedelicious.com/wp-content/uploads/2016/08/chicken-and-avocado-salad-6-of-10.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "12:00:00",
      quantity: 4
    }, {
      name: "Apple Turnover",
      type: "breakfast",
      description: "Great way to start your morning: fruit, pastry, and warmth!",
      photo_URL: "https://www.browneyedbaker.com/wp-content/uploads/2015/09/apple-turnovers-89-600A.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "12:00:00",
      quantity: 7
    },
  ]