module.exports = [
    {
      name: "Macaroni and Cheese",
      type: "lunch",
      description: "A cheesy delight that will not break your calorie budget!",
      photo_URL: "https://i.imgur.com/ndxGBYOm.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-05-25 18:28:00",
      quantity: 7,
      plateprice: 4.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60053,
      zipcode4: 60714,
      zipcode5: 60025,
      zipcode6: 60068,
      zipcode7: 60716,
      catererId: 2,
      UserId: 2
    },
    {
      name: "Homemade Pizza",
      type: "dinner",
      description: "A great blend of italian herbs, spinach, and three cheese. This pizza is a family tradition.",
      photo_URL: "https://i.imgur.com/RNRFeA2m.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available:  "2019-05-25 19:30:00",
      quantity: 5,
      plateprice: 5.49,
      zipcode1:60025,
      zipcode2: 60068,
      zipcode3: 60716,
      zipcode4: 60706,
      zipcode5: 60202,
      zipcode6: 60201,
      zipcode7: 60203,
      catererId: 2,
      UserId: 2
    }, {
      name: "Spring Bean Salad",
      type: "lunch",
      description: "A protein rich salad that will energize your afternoon.",
      photo_URL: "https://i.imgur.com/q6sUdnqm.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 0,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 1,
      date_available: "2019-05-26 20:30:00",
      quantity: 10,
      plateprice: 7.14,
      zipcode1:60202,
      zipcode2: 60201,
      zipcode3: 60203,
      zipcode4: 60631,
      zipcode5: 60645,
      zipcode6: 60626,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    }, {
      name: "Avocado and Chicken Salad",
      type: "dinner",
      description: "Scrumptious and meaty, yet smooth and flavorful.",
      photo_URL: "https://i.imgur.com/81tieiFm.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-05-26 21:15:00",
      quantity: 4,
      plateprice: 5.55,
      zipcode1:60626,
      zipcode2: 60660,
      zipcode3: 60659,
      zipcode4: 60646,
      zipcode5: 60712,
      zipcode6: 60645,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    }, {
      name: "Apple Turnover",
      type: "breakfast",
      description: "Great way to start your morning: fruit, pastry, and warmth!",
      photo_URL: "https://i.imgur.com/pi8FgBfm.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-27 22:00:00",
      quantity: 7,
      plateprice: 3.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60053,
      zipcode4: 60714,
      zipcode5: 60025,
      zipcode6: 60068,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },{
      name: "Spaghetti Delight",
      type: "dinner",
      description: "Hearty spaghetti with beef meatballs. Italian seasoning, generous portion.",
      photo_URL: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fcdn-image.myrecipes.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fmedium_2x%2Fpublic%2Fspaghetti-meatballs-tomato-basil-sauce-ck.jpg%3Fitok%3DkwzASYYP&w=450&c=sc&poi=face&q=85",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-28 22:00:00",
      quantity: 7,
      plateprice: 4.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },{
      name: "Tacos Galore",
      type: "dinner",
      description: "Healthy Tacos in hard shells or soft. Ground meat cooked in spices, topped with onion, tomatos, lettuce, and cheese.",
      photo_URL: "https://coda.newjobs.com/api/imagesproxy/ms/cms/content30/images/taco-bell.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-25 20:55:00",
      quantity: 7,
      plateprice: 3.59,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },
    {
      name: "Turkey Sandwich",
      type: "dinner",
      description: "Healthy whole grain bread, turkey, cheese, lettuce, and sauce.",
      photo_URL: "https://media.timeout.com/images/104101975/630/472/image.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-28 21:20:00",
      quantity: 7,
      plateprice: 2.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },{
      name: "Tomato Soup",
      type: "lunch",
      description: "Warm and hits the spot. Made with real tomatos, topped with cheddar cheese. Sides inlcude bread.",
      photo_URL: "https://www.theblackpeppercorn.com/wp-content/uploads/2012/02/Manhattan-Clam-Chowder-facebook-hires.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-26 16:50:00",
      quantity: 7,
      plateprice: 4.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },
    {
      name: "Chicken Corn Chowder",
      type: "dinner",
      description: "Creamed Corn, Mushrooms, Chicken bits, and light oregano. This chowder will fill and nourish.",
      photo_URL: "https://www.theblackpeppercorn.com/wp-content/uploads/2017/11/Chicken-Corn-Chowder-Soup-Recipe-overhead-hires.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-25 17:35:00",
      quantity: 7,
      plateprice: 6.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },
    {
      name: "Coca Cola Meatloaf",
      type: "dinner",
      description: "Coca Cola remininescing flavor in this hearty meatloaf will sooothe the tastebuds as the hearty portion fills.",
      photo_URL: "https://www.coca-colacompany.com/content/dam/journey/us/en/global/2012/10/MatchlessMeatLoaf-604-st-604-337-fe3c03f9.rendition.598.336.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-05-25 19:35:00",
      quantity: 7,
      plateprice: 7.99,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60605,
      zipcode4: 60604,
      zipcode5: 60602,
      zipcode6: 60601,
      zipcode7: 60654,
      catererId: 2,
      UserId: 2
    },
  ]

  // [
  //   {
  //     name: "Macaroni and Cheese",
  //     type: "lunch",
  //     description: "A cheesy delight that will not break your calorie budget!",
  //     photo_URL: "https://i.imgur.com/ndxGBYOm.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "11:00:00",
  //     quantity: 7,
  //     zipcodes: {
  //       zip: [60706, 60656, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   },
  //   {
  //     name: "Homemade Pizza",
  //     type: "dinner",
  //     description: "A great blend of italian herbs, spinach, and three cheese. This pizza is a family tradition.",
  //     photo_URL: "https://i.imgur.com/RNRFeA2m.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 1,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "19:00:00",
  //     quantity: 5,
  //     zipcodes: {
  //       zip: [60077, 60614, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Spring Bean Salad",
  //     type: "lunch",
  //     description: "A protein rich salad that will energize your afternoon.",
  //     photo_URL: "https://i.imgur.com/q6sUdnqm.jpg",
  //     allergen_dairy: 0,
  //     allergen_treenuts: 1,
  //     allergen_peanuts: 1,
  //     allergen_wheat: 0,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 1,
  //     date_available: "2019-04-21",
  //     time_available: "13:00:00",
  //     quantity: 10,
  //     zipcodes: {
  //       zip: [60077, 60614, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Avacado and Chicken Salad",
  //     type: "dinner",
  //     description: "Scrumptious and meaty, yet smooth and flavorful.",
  //     photo_URL: "https://i.imgur.com/81tieiFm.jpg",
  //     allergen_dairy: 0,
  //     allergen_treenuts: 1,
  //     allergen_peanuts: 1,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "12:00:00",
  //     quantity: 4,
  //     zipcodes: {
  //       zip: [60077, 60053, 60646, 60714, 60706]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Apple Turnover",
  //     type: "breakfast",
  //     description: "Great way to start your morning: fruit, pastry, and warmth!",
  //     photo_URL: "https://i.imgur.com/pi8FgBfm.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 1,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "12:00:00",
  //     quantity: 7,
  //     zipcodes: {
  //       zip: [60088, 60044, 60048, 60044, 60064, 60085]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }
  // ]