module.exports = [
    {
      name: "Macaroni and Cheese",
      type: "lunch",
      description: "A cheesy delight that will not break your calorie budget!",
      photo_URL: "https://i.imgur.com/ndxGBYOm.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "11:00:00",
      quantity: 7,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60053,
      zipcode4: 60714,
      zipcode5: 60025,
      zipcode6: 60068,
      zipcode7: 60716,
      catererId: 2,
      UserId: 2
    },
    {
      name: "Homemade Pizza",
      type: "dinner",
      description: "A great blend of italian herbs, spinach, and three cheese. This pizza is a family tradition.",
      photo_URL: "https://i.imgur.com/RNRFeA2m.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "19:00:00",
      quantity: 5,
      zipcode1:60025,
      zipcode2: 60068,
      zipcode3: 60716,
      zipcode4: 60706,
      zipcode5: 60202,
      zipcode6: 60201,
      zipcode7: 60203,
      catererId: 2,
      UserId: 2
    }, {
      name: "Spring Bean Salad",
      type: "lunch",
      description: "A protein rich salad that will energize your afternoon.",
      photo_URL: "https://i.imgur.com/q6sUdnqm.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 0,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 1,
      date_available: "2019-04-21",
      time_available: "13:00:00",
      quantity: 10,
      zipcode1:60202,
      zipcode2: 60201,
      zipcode3: 60203,
      zipcode4: 60631,
      zipcode5: 60645,
      zipcode6: 60626,
      zipcode7: 60660,
      catererId: 2,
      UserId: 2
    }, {
      name: "Avacado and Chicken Salad",
      type: "dinner",
      description: "Scrumptious and meaty, yet smooth and flavorful.",
      photo_URL: "https://i.imgur.com/81tieiFm.jpg",
      allergen_dairy: 0,
      allergen_treenuts: 1,
      allergen_peanuts: 1,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 0,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "12:00:00",
      quantity: 4,
      zipcode1:60626,
      zipcode2: 60660,
      zipcode3: 60659,
      zipcode4: 60646,
      zipcode5: 60712,
      zipcode6: 60645,
      zipcode7: 60631,
      catererId: 2,
      UserId: 2
    }, {
      name: "Apple Turnover",
      type: "breakfast",
      description: "Great way to start your morning: fruit, pastry, and warmth!",
      photo_URL: "https://i.imgur.com/pi8FgBfm.jpg",
      allergen_dairy: 1,
      allergen_treenuts: 0,
      allergen_peanuts: 0,
      allergen_wheat: 1,
      allergen_fish: 0,
      allergen_crustaceanshellfish: 0,
      allergen_eggs: 1,
      allergen_soya: 0,
      date_available: "2019-04-21",
      time_available: "12:00:00",
      quantity: 7,
      zipcode1:60077,
      zipcode2: 60076,
      zipcode3: 60053,
      zipcode4: 60714,
      zipcode5: 60025,
      zipcode6: 60068,
      zipcode7: 60716,
      catererId: 2,
      UserId: 2
    }
  ]

  // [
  //   {
  //     name: "Macaroni and Cheese",
  //     type: "lunch",
  //     description: "A cheesy delight that will not break your calorie budget!",
  //     photo_URL: "https://i.imgur.com/ndxGBYOm.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "11:00:00",
  //     quantity: 7,
  //     zipcodes: {
  //       zip: [60706, 60656, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   },
  //   {
  //     name: "Homemade Pizza",
  //     type: "dinner",
  //     description: "A great blend of italian herbs, spinach, and three cheese. This pizza is a family tradition.",
  //     photo_URL: "https://i.imgur.com/RNRFeA2m.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 1,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "19:00:00",
  //     quantity: 5,
  //     zipcodes: {
  //       zip: [60077, 60614, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Spring Bean Salad",
  //     type: "lunch",
  //     description: "A protein rich salad that will energize your afternoon.",
  //     photo_URL: "https://i.imgur.com/q6sUdnqm.jpg",
  //     allergen_dairy: 0,
  //     allergen_treenuts: 1,
  //     allergen_peanuts: 1,
  //     allergen_wheat: 0,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 1,
  //     date_available: "2019-04-21",
  //     time_available: "13:00:00",
  //     quantity: 10,
  //     zipcodes: {
  //       zip: [60077, 60614, 60049, 6819]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Avacado and Chicken Salad",
  //     type: "dinner",
  //     description: "Scrumptious and meaty, yet smooth and flavorful.",
  //     photo_URL: "https://i.imgur.com/81tieiFm.jpg",
  //     allergen_dairy: 0,
  //     allergen_treenuts: 1,
  //     allergen_peanuts: 1,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 0,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "12:00:00",
  //     quantity: 4,
  //     zipcodes: {
  //       zip: [60077, 60053, 60646, 60714, 60706]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }, {
  //     name: "Apple Turnover",
  //     type: "breakfast",
  //     description: "Great way to start your morning: fruit, pastry, and warmth!",
  //     photo_URL: "https://i.imgur.com/pi8FgBfm.jpg",
  //     allergen_dairy: 1,
  //     allergen_treenuts: 0,
  //     allergen_peanuts: 0,
  //     allergen_wheat: 1,
  //     allergen_fish: 0,
  //     allergen_crustaceanshellfish: 0,
  //     allergen_eggs: 1,
  //     allergen_soya: 0,
  //     date_available: "2019-04-21",
  //     time_available: "12:00:00",
  //     quantity: 7,
  //     zipcodes: {
  //       zip: [60088, 60044, 60048, 60044, 60064, 60085]
  //     },
  //     catererId: 2,
  //     UserId: 2
  //   }
  // ]